version: "3"

services:
  analyzer:
    container_name: analyzer_service
    build:
      context: .
      dockerfile: ./analyzer-dockerfile
    volumes:
      - ./analyzer:/analyzer
      - ./crawler:/crawler
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ["/bin/bash","-c"]
    command:
    - |
       /analyzer/mongo_install.sh
       mongod --fork --logpath=/home/user/mongo.log
       mongoimport --db=riskout --collection=counter --jsonArray --file=/home/user/analyzer/riskout_db.json
       pip install --no-cache-dir -r /analyzer/requirements.txt
       python /crawler/main.py
       python /analyzer/analyzer.py
