version: "3"

services:
  analyzer:
    container_name: analyzer_service
    build:
      context: .
      dockerfile: ./analyzer-dockerfile
    volumes:
      - ./analyzer:/analyzer
      - ./crawler:/crawler
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint: ["/bin/bash","-c"]
    command:
      - |
        pip install --no-cache-dir -r /analyzer/requirements.txt
        python /crawler/main.py
        python /analyzer/analyzer.py
    depends_on:
      - mongo

  mongo:
    container_name: mongo_service
    image: mongo:4.4
    volumes:
      - ./analyzer/data:/data
    expose:
      - "27017"
  
  mongo-seed:
    container_name: mongo-seed_service
    build:
      context: .
      dockerfile: ./analyzer-dockerfile
    depends_on:
      - mongo
